version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=api_project
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=047b3d73d344c012f151f37cb5c2a4a4912a6f4449eb7bb645bb095faa507798
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=api_project
    expose:
      - 5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: {}